SELECT LOCATION_NAME, REGION, POSTAL_CODE, median_spend_per_customer
FROM THERAREBURGER.PUBLIC.MONTHLY_REVENUE WHERE POSTAL_CODE IN ('10036', '10019', '10003') UNION SELECT LOCATION_NAME, REGION, POSTAL_CODE, median_spend_per_customer  
FROM FREE_SAMPLE_CROSS_SHOPPING_INSIGHTS__NYC_RESTAURANTS.PUBLIC.SPEND_CROSS_SHOPPING_SAMPLE 
WHERE CATEGORY_TAGS LIKE '%Burger%'AND POSTAL_CODE IN ('10036', '10019', '10003');