SELECT LOCATION_NAME, REGION, POSTAL_CODE, RAW_NUM_CUSTOMERS 
FROM THERAREBURGER.PUBLIC.MONTHLY_REVENUE UNION SELECT LOCATION_NAME, REGION, POSTAL_CODE, RAW_NUM_CUSTOMERS  
FROM FREE_SAMPLE_CROSS_SHOPPING_INSIGHTS__NYC_RESTAURANTS.PUBLIC.SPEND_CROSS_SHOPPING_SAMPLE 
WHERE CATEGORY_TAGS LIKE '%Burger%';