SELECT LOCATION_NAME, REGION, POSTAL_CODE, online_spend 
FROM THERAREBURGER.PUBLIC.MONTHLY_REVENUE UNION SELECT LOCATION_NAME, REGION, POSTAL_CODE, online_spend  
FROM FREE_SAMPLE_CROSS_SHOPPING_INSIGHTS__NYC_RESTAURANTS.PUBLIC.SPEND_CROSS_SHOPPING_SAMPLE 
WHERE CATEGORY_TAGS LIKE '%Burger%';